// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYrX1jvi9qrVP0aSV3VJdF3Ae-kJD1_v4',
    appId: '1:47512341921:web:90676a8607a9e9fff50fe0',
    messagingSenderId: '47512341921',
    projectId: 'modelomvvm',
    authDomain: 'modelomvvm.firebaseapp.com',
    storageBucket: 'modelomvvm.firebasestorage.app',
    measurementId: 'G-TD8RN2V6FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIDN9Ud07JXTxvY5otq4FBFaRq7BCaCQ',
    appId: '1:47512341921:android:a03a2e4e7c20c845f50fe0',
    messagingSenderId: '47512341921',
    projectId: 'modelomvvm',
    storageBucket: 'modelomvvm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbNHXuntQq8UJN0Z5Mo0q8kBWZXS0O4E',
    appId: '1:47512341921:ios:cac2482d092d9004f50fe0',
    messagingSenderId: '47512341921',
    projectId: 'modelomvvm',
    storageBucket: 'modelomvvm.firebasestorage.app',
    iosBundleId: 'com.example.modeloMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbNHXuntQq8UJN0Z5Mo0q8kBWZXS0O4E',
    appId: '1:47512341921:ios:cac2482d092d9004f50fe0',
    messagingSenderId: '47512341921',
    projectId: 'modelomvvm',
    storageBucket: 'modelomvvm.firebasestorage.app',
    iosBundleId: 'com.example.modeloMvvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYrX1jvi9qrVP0aSV3VJdF3Ae-kJD1_v4',
    appId: '1:47512341921:web:e195c57ada2f9e94f50fe0',
    messagingSenderId: '47512341921',
    projectId: 'modelomvvm',
    authDomain: 'modelomvvm.firebaseapp.com',
    storageBucket: 'modelomvvm.firebasestorage.app',
    measurementId: 'G-PTP8KZHTJQ',
  );
}
